name: lp_launcher
decription: Modules communs pour les projets

version: 1.0.0
homepage: https://github.com/devobs/flutter

environment:
  flutter: ">=3.0.1 <4.0.0"
  sdk: '>=2.17.1 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2
  quiver: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1